server:
  port: 8021
spring:
  application:
    name: eureka-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8021/eureka/
    instance:
      metadataMap:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}