server:
  port: 8710
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marshalYuan/spring-cloud-example
          search-paths: config-repo
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/